add_newline = false

format = """
$username\
@\
$hostname\
[\uE0B0](fg:vt_blue inverted)\
$directory\
[\uE0B0](fg:vt_blue)\
[\uE0B0](fg:vt_green inverted)\
$git_branch\
$git_status\
[\uE0B0](fg:vt_green)\
[\uE0B0](fg:vt_purple inverted)\
$memory_usage\
$cmd_duration\
[\uE0B0](fg:vt_purple)\
$line_break\
$character"""

palette = 'vetus'

right_format = """
[\uE0B2](fg:vt_yellow)\
$time\
[\uE0B2](fg:vt_yellow inverted)\
"""

[palettes.vetus]
vt_black = "#19191A"
vt_blue = "#79B8FF"
vt_green = "#95FFA4"
vt_purple = "#7160E8"
vt_red = "#EA4A5A"
vt_white = "#EBEDF2"
vt_yellow = "#FFC073"

[username]
format = '[  $user]($style)'
show_always = true
style_user = "fg:none"

[hostname]
format = '[$hostname ]($style)'
ssh_only = false
style = "fg:none"

[directory]
format = "[ $path ]($style)"
style = "bg:vt_blue fg:vt_black"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
format = '[ $symbol $branch ]($style)'
style = "bg:vt_green fg:vt_black"
symbol = "\uE0A0"

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "bg:vt_green fg:vt_black"

[time]
disabled = false
format = '[ $time ]($style)'
style = "bg:vt_yellow fg:vt_black"

[memory_usage]
disabled = false
format = "[ ${ram} ]($style)"
style = "bg:vt_purple fg:vt_white"
threshold = 50

[cmd_duration]
format = "[ $duration ]($style)"
min_time = 16
style = "bg:vt_purple fg:vt_white"

[line_break]
disabled = false

[character]
error_symbol = "[\u276F](fg:vt_red)"
success_symbol = "[\u276F](fg:vt_green)"
